# Generated by Django 3.2.5 on 2021-07-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
