# Generated by Django 3.2.5 on 2021-07-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.todolist'),
            preserve_default=False,
        ),
    ]
