# Generated by Django 3.2.5 on 2021-07-16 02:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_todo_todo_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('user', 'name')},
        ),
    ]
